const lemonJuice = 'Lemon Juice';
const ordinaryDrink = 'Ordinary Drink';
const cocktailGlass = 'Cocktail glass';
const grandMarnier = 'Grand Marnier';

export const Drinks = {
  drinks: [
    {
      idDrink: '15997',
      strDrink: 'GG',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Optional alcohol',
      strGlass: 'Collins Glass',
      strInstructions: 'Pour the Galliano liqueur over ice. \r\n'
      + 'Fill the remainder of the glass with ginger ale and \r\n'
      + 'thats all there is to it. You now have a your very own GG.',
      strInstructionsES: null,
      strInstructionsDE: 'Den Galliano-Lik\u00F6r \u00FCber Eis \r\n'
      + 'gie\u00DFen. F\u00FCllen Sie den Rest des Glases mit \r\n'
      + 'Ginger Ale und das ist alles, was dazu geh\u00F6rt. \r\n'
      + 'Du hast jetzt ein eigenes GG.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare il liquore Galliano su ghiaccio.\r\n'
      + 'Riempi il resto del bicchiere con ginger ale e questo \u00E8 tutto.\r\n'
      + 'Ora hai il tuo GG personale.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
      strIngredient1: 'Galliano',
      strIngredient2: 'Ginger ale',
      strIngredient3: 'Ice',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 1/2 shots ',
      strMeasure2: null,
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-18 22:06:00',
    },
    {
      idDrink: '17222',
      strDrink: 'A1',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: cocktailGlass,
      strInstructions: 'Pour all ingredients \r\n'
      + 'into a cocktail shaker, mix and\r\n'
      + ' serve over ice into a chilled glass.',
      strInstructionsES: 'Vierta todos los \r\n'
      + 'ingredientes en una coctelera, \r\n'
      + 'mezcle y sirva con hielo en un vaso fr\u00EDo.',
      strInstructionsDE: 'Alle Zutaten in \r\n'
      + 'einen Cocktailshaker geben, mischen und\r\n'
      + ' \u00FCber Eis in ein gek\u00FChltes Glas servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare tutti gli \r\n'
      + 'ingredienti in uno shaker, mescolare \r\n'
      + 'e servire con ghiaccio in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
      strIngredient1: 'Gin',
      strIngredient2: grandMarnier,
      strIngredient3: lemonJuice,
      strIngredient4: 'Grenadine',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 3/4 shot ',
      strMeasure2: '1 Shot ',
      strMeasure3: '1/4 Shot',
      strMeasure4: '1/8 Shot',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 21:42:09',
    },
    {
      idDrink: '17225',
      strDrink: 'Ace',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake all the ingredients\r\n'
      + ' in a cocktail shaker and ice then strain\r\n'
      + ' in a cold glass.',
      strInstructionsES: 'Agite todos los ingredientes\r\n'
      + ' en una coctelera con hielo y entonces \r\n'
      + 'cu\u00E9lelos sobre un vaso enfriado.',
      strInstructionsDE: 'Alle Zutaten in einem \r\n'
      + 'Cocktailshaker mit Eis sch\u00FCtteln \r\n'
      + 'und dann in einem kalten Glas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli \r\n'
      + 'ingredienti in uno shaker e ghiaccio,\r\n'
      + ' quindi filtrare in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grenadine',
      strIngredient3: 'Heavy cream',
      strIngredient4: 'Milk',
      strIngredient5: 'Egg White',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 shots ',
      strMeasure2: '1/2 shot ',
      strMeasure3: '1/2 shot ',
      strMeasure4: '1/2 shot',
      strMeasure5: '1/2 Fresh',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 22:05:06',
    }],
};
