const mincedBeef = 'Minced Beef';
const garlicClove = 'Garlic Clove';
const vegetableOil = 'Vegetable Oil';
const lemonJuice = 'Lemon Juice';
const ordinaryDrink = 'Ordinary Drink';
const cocktailGlass = 'Cocktail glass';
const grandMarnier = 'Grand Marnier';
const shotGlass = 'Shot glass';
const baileysIrishCream = 'Baileys irish cream';

export const mockMealsData = {
  meals: [
    {
      idMeal: '52977',
      strMeal: 'Corba',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strInstructions:
  'Pick through your lentils for any foreign debris, \r\n'
  + 'rinse them 2 or 3 times, drain, and set aside.\r\n'
  + 'Fair warning, this will probably turn your lentils into a \r\n'
  + 'solid block that you’ll have to break up later\r\n'
  + 'In a large pot over medium-high heat, sauté the olive oil and \r\n'
  + 'the onion with a pinch of salt for about 3 minutes, then add the \r\n'
  + 'carrots and cook for another 3 minutes.\r\n'
  + 'Add the tomato paste and stir it around for around 1 minute.\r\n'
  + 'Now add the cumin, paprika, mint, thyme, black pepper, and red pepper\r\n'
  + 'as quickly as you can and stir for 10 seconds to bloom the spices.\r\n'
  + 'Congratulate yourself on how amazing your house now smells.\r\n'
  + 'Immediately add the lentils, water, broth, and salt.\r\n'
  + 'Bring the soup to a (gentle) boil.\r\n'
  + 'After it has come to a boil, reduce heat to medium-low, cover the pot\r\n'
  + 'halfway, and cook for 15-20 minutes or until the lentils have fallen apart\r\n'
  + 'and the carrots are completely cooked.\r\n'
  + 'After the soup has cooked and the lentils are tender,\r\n'
  + 'blend the soup either in a blender or simply use a hand blender\r\n'
  + 'to reach the consistency you desire.\r\n'
  + 'Taste for seasoning and add more salt if necessary.\r\n'
  + 'Serve with crushed-up crackers, torn up bread, or something\r\n'
  + 'else to add some extra thickness.\r\n'
  + 'You could also use a traditional thickener (like cornstarch or flour),\r\n'
  + 'but I prefer to add crackers for some texture and saltiness.\r\n'
  + 'Makes great leftovers, stays good in the fridge for about a week.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
      strIngredient1: 'Lentils',
      strIngredient2: 'Onion',
      strIngredient3: 'Carrots',
      strIngredient4: 'Tomato Puree',
      strIngredient5: 'Cumin',
      strIngredient6: 'Paprika',
      strIngredient7: 'Mint',
      strIngredient8: 'Thyme',
      strIngredient9: 'Black Pepper',
      strIngredient10: 'Red Pepper Flakes',
      strIngredient11: 'Vegetable Stock',
      strIngredient12: 'Water',
      strIngredient13: 'Sea Salt',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 cup ',
      strMeasure2: '1 large',
      strMeasure3: '1 large',
      strMeasure4: '1 tbs',
      strMeasure5: '2 tsp',
      strMeasure6: '1 tsp ',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1/2 tsp',
      strMeasure9: '1/4 tsp',
      strMeasure10: '1/4 tsp',
      strMeasure11: '4 cups ',
      strMeasure12: '1 cup ',
      strMeasure13: 'Pinch',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53060',
      strMeal: 'Burek',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Croatian',
      strInstructions: 'Fry the finely chopped onions and minced meat in oil.\r\n'
      + 'Add the salt and pepper. Grease a round baking \r\n'
      + 'tray and put a layer of pastry\r\n'
      + 'in it. Cover with a thin layer of filling and \r\n'
      + 'cover this with another layer of \r\n'
      + 'filo pastry which must be well coated in oil. \r\n'
      + 'Put another layer of filling and cover\r\n'
      + 'with pastry. When you have five or six layers, \r\n'
      + 'cover with filo pastry, bake at\r\n'
      + '200\u00BAC/392\u00BAF for half an hour and cut in quarters and serve.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
      strTags: 'Streetfood, Onthego',
      strYoutube: 'https://www.youtube.com/watch?v=YsJXZwE5pdY',
      strIngredient1: 'Filo Pastry',
      strIngredient2: mincedBeef,
      strIngredient3: 'Onion',
      strIngredient4: 'Oil',
      strIngredient5: 'Salt',
      strIngredient6: 'Pepper',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 Packet',
      strMeasure2: '150g',
      strMeasure3: '150g',
      strMeasure4: '40g',
      strMeasure5: 'Dash',
      strMeasure6: 'Dash',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53065',
      strMeal: 'Sushi',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Japanese',
      strInstructions: 'STEP 1\r\n'
      + 'TO MAKE SUSHI ROLLS: Pat out some rice.\r\n'
      + ' Lay a nori sheet on the mat, shiny-side down.\r\n'
      + ' Dip your hands in the vinegared water, then pat\r\n'
      + ' handfuls of rice on top in a 1cm thick layer,\r\n'
      + ' leaving the furthest edge from you clear.\r\n\r\n'
      + 'STEP 2\r\nSpread over some Japanese mayonnaise. \r\n'
      + 'Use a spoon to spread out a thin layer of mayonnaise\r\n'
      + ' down the middle of the rice.\r\n\r\n'
      + 'STEP 3\r\nAdd the filling. Get your child to top\r\n'
      + ' the mayonnaise with a line of their favourite \r\n'
      + 'fillings \u2013 here we\u2019ve used tuna and cucumber.\r\n\r\n'
      + 'STEP 4\r\nRoll it up. Lift the edge of the mat over the rice,\r\n'
      + ' applying a little pressure to keep everything in a tight roll.\r\n\r\n'
      + 'STEP 5\r\nStick down the sides like a stamp. When you get to the\r\n'
      + ' edge without any rice, brush with a little water\r\n'
      + ' and continue to roll into a tight roll.\r\n\r\n'
      + 'STEP 6\r\nWrap in cling film. Remove the mat and roll\r\n'
      + ' tightly in cling film before a grown-up cuts the sushi\r\n'
      + ' into thick slices, then unravel the cling film.\r\n\r\n'
      + 'STEP 7\r\nTO MAKE PRESSED SUSHI: Layer over some smoked \r\n'
      + 'salmon. Line a loaf tin with cling film, then place a thin \r\n'
      + 'layer of smoked salmon inside on top of the cling film.\r\n\r\n'
      + 'STEP 8\r\nCover with rice and press down. Press about 3cm of \r\n'
      + 'rice over the fish, fold the cling film over and press down as \r\n'
      + 'much as you can, using another tin if you have one.\r\n\r\n'
      + 'STEP 9\r\nTip it out like a sandcastle. Turn block of sushi \r\n'
      + 'onto a chopping board. Get a grown-up to cut into fingers, then \r\n'
      + 'remove the cling film.\r\n\r\nSTEP 10\r\nTO MAKE SUSHI BALLS: \r\n'
      + 'Choose your topping. Get a small square of cling film and place a \r\n'
      + 'topping, like half a prawn or a small piece of smoked salmon, on it. \r\n'
      + 'Use damp hands to roll walnut-sized balls \r\n'
      + 'of rice and place on the topping.\r\n\r\n'
      + 'STEP 11\r\nMake into tight balls. Bring the corners \r\n'
      + 'of the cling film together and tighten into balls by \r\n'
      + 'twisting it up, then unwrap and serve.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
      strIngredient1: 'Sushi Rice',
      strIngredient2: 'Rice wine',
      strIngredient3: 'Caster Sugar',
      strIngredient4: 'Mayonnaise',
      strIngredient5: 'Rice wine',
      strIngredient6: 'Soy Sauce',
      strIngredient7: 'Cucumber',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '300ml ',
      strMeasure2: '100ml',
      strMeasure3: '2 tbs',
      strMeasure4: '3 tbs',
      strMeasure5: '1 tbs',
      strMeasure6: '1 tbs',
      strMeasure7: '1',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.bbcgoodfood.com/recipes/simple-sushi',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52978',
      strMeal: 'Kumpir',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strInstructions: 'If you order kumpir in Turkey, the standard \r\n'
      + 'filling is first, lots of butter mashed into the potato, \r\n'
      + 'followed by cheese. There\u2019s then a row of other toppings\r\n'
      + ' that you can just point at to your heart\u2019s content\r\n\r\n'
      + ' \u2013 sweetcorn, olives, salami, coleslaw, Russian salad,\r\n'
      + ' allsorts \u2013 and you walk away with an over-stuffed potato \r\n'
      + 'because you got ever-excited by the choices on offer.\r\n\r\n'
      + 'Grate (roughly \u2013 you can use as much as you like) 150g \r\n'
      + 'of cheese.\r\nFinely chop one onion and one sweet red pepper.\r\n'
      + 'Put these ingredients into a large bowl with a good sprinkling \r\n'
      + 'of salt and pepper, chilli flakes (optional).',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
      strTags: 'SideDish',
      strYoutube: 'https://www.youtube.com/watch?v=IEDEtZ4UVtI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Butter',
      strIngredient3: 'Cheese',
      strIngredient4: 'Onion',
      strIngredient5: 'Red Pepper',
      strIngredient6: 'Red Chile Flakes',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 large',
      strMeasure2: '2 tbs',
      strMeasure3: '150g',
      strMeasure4: '1 large',
      strMeasure5: '1 large',
      strMeasure6: 'Pinch',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://www.turkeysforlife.com/2013/10/firinda-kumpir-turkish-street-food.html',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53069',
      strMeal: 'Bistek',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'Filipino',
      strInstructions: '0.\tMarinate beef in soy sauce,\r\n'
      + ' lemon (or calamansi), and ground black pepper \r\n'
      + 'for at least 1 hour. Note: marinate overnight for \r\n'
      + 'best result\r\n1.\tHeat the cooking oil in a pan \r\n'
      + 'then pan-fry half of the onions until the texture\r\n'
      + ' becomes soft. Set aside\r\n2.\tDrain the marinade \r\n'
      + 'from the beef. Set it aside. Pan-fry the beef on \r\n'
      + 'the same pan where the onions were fried for 1 \r\n'
      + 'minute per side. Remove from the pan. Set aside\r\n'
      + '3.\tAdd more oil if needed. Saute garlic and \r\n'
      + 'remaining raw onions until onion softens.\r\n'
      + '4.\tPour the remaining marinade and water. Bring\r\n'
      + ' to a boil.\r\n5.\tAdd beef. Cover the pan and \r\n'
      + 'simmer until the meat is tender. Note: Add water \r\n'
      + 'as needed.\r\n6.\tSeason with ground black pepper \r\n'
      + 'and salt as needed. Top with pan-fried onions.\r\n'
      + '7.\tTransfer to a serving plate. Serve hot. Share and Enjoy!\r\n',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/4pqimk1683207418.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=xOQON5_S7as',
      strIngredient1: 'Beef',
      strIngredient2: 'Soy Sauce',
      strIngredient3: 'Lemon',
      strIngredient4: 'Garlic',
      strIngredient5: 'Onion',
      strIngredient6: 'Olive Oil',
      strIngredient7: 'Water',
      strIngredient8: 'Salt',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 lb',
      strMeasure2: '5 tablespoons',
      strMeasure3: '1',
      strMeasure4: '3 cloves',
      strMeasure5: '3 parts ',
      strMeasure6: '4 tbs',
      strMeasure7: '1 cup ',
      strMeasure8: '1 pinch',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://panlasangpinoy.com/bistek-tagalog-beefsteak-recipe/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53026',
      strMeal: 'Tamiya',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strInstructions: 'oak the beans in water to cover overnight\r\n'
      + '.Drain. If skinless beans are unavailable, rub to loosen \r\n'
      + 'the skins, then discard the skins. Pat the beans dry with a towel.\r\n'
      + 'Grind the beans in a food mill or meat grinder.If neither \r\n'
      + 'appliance is available, process them in a food processor but only \r\n'
      + 'until the beans form a paste. (If blended too smoothly, the batter\r\n'
      + ' tends to fall apart during cooking.) Add the scallions, garlic,\r\n'
      + ' cilantro, cumin, baking powder, cayenne, salt, pepper, and \r\n'
      + 'coriander, if using.  Refrigerate for at least 30 minutes.\r\n'
      + 'Shape the bean mixture into 1-inch balls.Flatten slightly \r\n'
      + 'and coat with flour.\r\nHeat at least 1\u00BD-inches of oil \r\n'
      + 'over medium heat to 365 degrees.\r\nFry the patties in batches,\r\n'
      + ' turning once, until golden brown on all sides, about 5 minutes.\r\n'
      + 'Remove with a wire mesh skimmer or slotted spoon. Serve as part \r\n'
      + 'of a meze or in pita bread with tomato-cucumber salad and tahina sauce.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
      strIngredient1: 'Broad Beans',
      strIngredient2: 'Spring Onions',
      strIngredient3: garlicClove,
      strIngredient4: 'Parsley',
      strIngredient5: 'Cumin',
      strIngredient6: 'Baking Powder',
      strIngredient7: 'Cayenne Pepper',
      strIngredient8: 'Flour',
      strIngredient9: vegetableOil,
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 cups ',
      strMeasure2: '6',
      strMeasure3: '4',
      strMeasure4: '1/4 cup',
      strMeasure5: '2 tsp',
      strMeasure6: '1 tsp ',
      strMeasure7: '1/2 tsp',
      strMeasure8: 'Spinkling',
      strMeasure9: 'As required',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52971',
      strMeal: 'Kafteji',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Tunisian',
      strInstructions: 'Peel potatoes and cut into 5cm cubes.\r\n'
      + 'Pour 1-2 cm of olive oil into a large pan and heat up \r\n'
      + 'very hot. Fry potatoes until golden brown for 20 minutes, \r\n'
      + 'turning from time to time. Place on kitchen paper to drain.\r\n'
      + 'Cut the peppers in half and remove seeds. Rub a little olive\r\n'
      + ' oil on them and place the cut side down on a baking tray. Place\r\n'
      + ' them under the grill. Grill until the skin is dark and bubbly.\r\n'
      + ' While the peppers are still hot, put them into a plastic sandwich\r\n'
      + ' bag and seal it. Take them out after 15 minutes and remove skins.\r\n'
      + 'In the meantime, heat more olive oil another pan. Peel the onions \r\n'
      + 'and cut into thin rings. Fry for 15 minutes until golden brown, \r\n'
      + 'turning them often. Add the Ras el hanout at the end.\r\n'
      + 'Cut the pumpkin into 5cm cubes and fry in the same pan \r\n'
      + 'you used for the potatoes for 10-15 minutes until it is soft\r\n'
      + ' and slightly browned. Place on kitchen paper.\r\n'
      + 'Pour the remaining olive oil out of the pan and put \r\n'
      + 'all the cooked vegetables into the pan and mix. Whisk \r\n'
      + 'eggs and pour them over the vegetables. Put the lid on\r\n'
      + ' the pan so that the eggs cook. Put the contents of the\r\n'
      + ' pan onto a large chopping board, add salt and pepper\r\n'
      + ' and chopped and mix everything with a big knife.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=-TFf-Zu-xQU',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Green Pepper',
      strIngredient4: 'Onions',
      strIngredient5: 'Ras el hanout',
      strIngredient6: 'Pumpkin',
      strIngredient7: 'Eggs',
      strIngredient8: 'Salt',
      strIngredient9: 'Pepper',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '5 Large',
      strMeasure2: '2 tbs',
      strMeasure3: '1',
      strMeasure4: '5',
      strMeasure5: '1 tbs',
      strMeasure6: '500g',
      strMeasure7: '24 Skinned',
      strMeasure8: 'Pinch',
      strMeasure9: 'Pinch',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://allrecipes.co.uk/recipe/12294/kafteji--tunisian-fried-vegetables-.aspx',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52844',
      strMeal: 'Lasagne',
      strDrinkAlternate: null,
      strCategory: 'Pasta',
      strArea: 'Italian',
      strInstructions: 'Heat the oil in a large saucepan. \r\n'
      + 'Use kitchen scissors to snip the bacon into small pieces,\r\n'
      + ' or use a sharp knife to chop it on a chopping board.\r\n'
      + ' Add the bacon to the pan and cook for just a few mins\r\n'
      + ' until starting to turn golden. Add the onion, celery \r\n'
      + 'and carrot, and cook over a medium heat for 5 mins, \r\n'
      + 'stirring occasionally, until softened.\r\n'
      + 'Add the garlic and cook for 1 min, then tip in the \r\n'
      + 'mince and cook, stirring and breaking it up with a wooden \r\n'
      + 'spoon, for about 6 mins until browned all over.\r\n'
      + 'Stir in the tomato pur\u00E9e and cook for 1 min, \r\n'
      + 'mixing in well with the beef and vegetables. Tip in the\r\n'
      + ' chopped tomatoes. Fill each can half full with water to\r\n'
      + ' rinse out any tomatoes left in the can, and add to the pan.\r\n'
      + ' Add the honey and season to taste. Simmer for 20 mins.\r\n'
      + 'Heat oven to 200C/180C fan/gas 6. To assemble the lasagne,\r\n'
      + ' ladle a little of the ragu sauce into the bottom of the \r\n'
      + 'roasting tin or casserole dish, spreading the sauce all over\r\n'
      + ' the base. Place 2 sheets of lasagne on top of the sauce \r\n'
      + 'overlapping to make it fit, then repeat with more sauce \r\n'
      + 'and another layer of pasta. Repeat with a further 2 layers \r\n'
      + 'of sauce and pasta, finishing with a layer of pasta.\r\n'
      + 'Put the cr\u00E8me fra\u00EEche in a bowl and mix with \r\n'
      + '2 tbsp water to loosen it and make a smooth pourable sauce.\r\n'
      + ' Pour this over the top of the pasta, then top with the \r\n'
      + 'mozzarella. Sprinkle Parmesan over the top and bake\r\n'
      + ' for 25\u201330 mins until golden and bubbling. Serve\r\n'
      + ' scattered with basil, if you like.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=gfhfsBPt46s',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Bacon',
      strIngredient3: 'Onion',
      strIngredient4: 'Celery',
      strIngredient5: 'Carrots',
      strIngredient6: 'Garlic',
      strIngredient7: mincedBeef,
      strIngredient8: 'Tomato Puree',
      strIngredient9: 'Chopped Tomatoes',
      strIngredient10: 'Honey',
      strIngredient11: 'Lasagne Sheets',
      strIngredient12: 'Creme Fraiche',
      strIngredient13: 'Mozzarella Balls',
      strIngredient14: 'Parmesan Cheese',
      strIngredient15: 'Basil Leaves',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 tblsp ',
      strMeasure2: '2',
      strMeasure3: '1 finely chopped ',
      strMeasure4: '1 Stick',
      strMeasure5: '1 medium',
      strMeasure6: '2 cloves chopped',
      strMeasure7: '500g',
      strMeasure8: '1 tbls',
      strMeasure9: '800g',
      strMeasure10: '1 tblsp ',
      strMeasure11: '500g',
      strMeasure12: '400ml',
      strMeasure13: '125g',
      strMeasure14: '50g',
      strMeasure15: 'Topping',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/classic-lasagne',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52785',
      strMeal: 'Dal fry',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Indian',
      strInstructions: 'Wash and soak toor dal in approx.\r\n'
      + ' 3 cups of water, for at least one hours. Dal \r\n'
      + 'will be double in volume after soaking. Drain the water.\r\n'
      + 'Cook dal with 2-1/2 cups water and add salt, \r\n'
      + 'turmeric, on medium high heat, until soft in \r\n'
      + 'texture (approximately 30 mins) it should be \r\n'
      + 'like thick soup.\r\nIn a frying pan, heat the ghee.\r\n'
      + ' Add cumin seeds, and mustard seeds. After the \r\n'
      + 'seeds crack, add bay leaves, green chili, ginger and\r\n'
      + ' chili powder. Stir for a few seconds.\r\n'
      + 'Add tomatoes, salt and sugar stir and cook until \r\n'
      + 'tomatoes are tender and mushy.\r\nAdd cilantro and \r\n'
      + 'garam masala cook for about one minute.\r\n'
      + 'Pour the seasoning over dal mix it well and \r\n'
      + 'cook for another minute.\r\nServe with Naan.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
      strTags: 'Curry,Vegetarian,Cake',
      strYoutube: 'https://www.youtube.com/watch?v=J4D855Q9-jg',
      strIngredient1: 'Toor dal',
      strIngredient2: 'Water',
      strIngredient3: 'Salt',
      strIngredient4: 'Turmeric',
      strIngredient5: 'Ghee',
      strIngredient6: 'Chopped tomatoes',
      strIngredient7: 'Cumin seeds',
      strIngredient8: 'Mustard Seeds',
      strIngredient9: 'Bay Leaf',
      strIngredient10: 'Green Chili',
      strIngredient11: 'Ginger',
      strIngredient12: 'Cilantro',
      strIngredient13: 'Red Pepper',
      strIngredient14: 'Salt',
      strIngredient15: 'Sugar',
      strIngredient16: 'Garam Masala',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 cup',
      strMeasure2: '2-1/2 cups',
      strMeasure3: '1 tsp',
      strMeasure4: '1/4 tsp',
      strMeasure5: '3 tbs',
      strMeasure6: '1 cup',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1/2 tsp',
      strMeasure9: '2',
      strMeasure10: '1 tbs chopped',
      strMeasure11: '2 tsp shredded',
      strMeasure12: '2 tbs ',
      strMeasure13: '1/2 tsp',
      strMeasure14: '1/2 tsp',
      strMeasure15: '1 tsp',
      strMeasure16: '1/4 tsp',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.instagram.com/p/BO21bpYD3Fu',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52948',
      strMeal: 'Wontons',
      strDrinkAlternate: null,
      strCategory: 'Pork',
      strArea: 'Chinese',
      strInstructions: 'Combine pork, garlic, ginger, soy sauce, \r\n'
      + 'sesame oil, and vegetables in a bowl.\r\nSeparate wonton skins.\r\n'
      + 'Place a heaping teaspoon of filling in the center of the wonton.\r\n'
      + 'Brush water on 2 borders of the skin, covering 1/4 inch from the edge.\r\n'
      + 'Fold skin over to form a triangle, sealing edges.\r\n'
      + 'Pinch the two long outside points together.\r\n'
      + 'Heat oil to 450 degrees and fry 4 to 5 at a time until golden.\r\n'
      + 'Drain and serve with sauce.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1525876468.jpg',
      strTags: 'MainMeal',
      strYoutube: 'https://www.youtube.com/watch?v=9h9No18ZyCI',
      strIngredient1: 'Pork',
      strIngredient2: garlicClove,
      strIngredient3: 'Ginger',
      strIngredient4: 'Soy Sauce',
      strIngredient5: 'Sesame Seed Oil',
      strIngredient6: 'Carrots',
      strIngredient7: 'Celery',
      strIngredient8: 'Spring Onions',
      strIngredient9: 'Wonton Skin',
      strIngredient10: 'Oil',
      strIngredient11: 'Water',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1lb',
      strMeasure2: '3 chopped',
      strMeasure3: '1 tsp ',
      strMeasure4: '1 tbs',
      strMeasure5: '1 tsp ',
      strMeasure6: '3 finely chopped',
      strMeasure7: '3 finely chopped',
      strMeasure8: '6 chopped',
      strMeasure9: '1 Packet',
      strMeasure10: 'Fry',
      strMeasure11: 'Bottle',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.geniuskitchen.com/recipe/chinese-wontons-20235',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strInstructions: 'Heat oil in a deep fryer or deep heavy \r\n'
      + 'skillet to 365\u00B0F (185\u00B0C).\r\n'
      + 'Warm gravy in saucepan or microwave.\r\n'
      + 'Place the fries into the hot oil, and cook until light brown,\r\n'
      + ' about 5 minutes.\r\nRemove to a paper towel lined plate to drain.\r\n'
      + 'Place the fries on a serving platter, and sprinkle the cheese over them.\r\n'
      + 'Ladle gravy over the fries and cheese, and serve immediately.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      strIngredient1: vegetableOil,
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: 'Dash',
      strMeasure2: '1 Can',
      strMeasure3: '5 thin cut',
      strMeasure4: '2 cups',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52929',
      strMeal: 'Timbits',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strInstructions: 'Sift together dry ingredients.\r\n'
      + 'Mix together wet ingredients and incorporate into dry. Stir until smooth.\r\n'
      + 'Drop by teaspoonfuls(no bigger) into hot oil \r\n'
      + '(365 degrees, no hotter), turning after a few moments until\r\n'
      + ' golden brown on all sides.\r\nRemove and drain.\r\n'
      + 'Roll in cinnamon sugar while still warm and serve.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
      strTags: 'Snack,Treat',
      strYoutube: 'https://www.youtube.com/watch?v=fFLn1h80AGQ',
      strIngredient1: 'Flour',
      strIngredient2: 'Sugar',
      strIngredient3: 'Baking Powder',
      strIngredient4: 'Salt',
      strIngredient5: 'Egg',
      strIngredient6: 'Milk',
      strIngredient7: 'Oil',
      strIngredient8: 'Oil',
      strIngredient9: 'Icing Sugar',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 cups ',
      strMeasure2: '1/3 cup',
      strMeasure3: '3 tsp',
      strMeasure4: '\u00BD tsp',
      strMeasure5: '1 beaten',
      strMeasure6: '\u00BE cup',
      strMeasure7: '3 tbs',
      strMeasure8: 'for frying',
      strMeasure9: 'garnish',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.geniuskitchen.com/recipe/drop-doughnuts-133877',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53027',
      strMeal: 'Koshari',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strInstructions: 'Cook the lentils. Bring lentils\r\n'
      + ' and 4 cups of water to a boil in a medium pot or \r\n'
      + 'saucepan over high heat. Reduce the heat to low and \r\n'
      + 'cook until lentils are just tender (15-17 minutes). \r\n'
      + 'Drain from water and season with a little salt. \r\n'
      + '(Note: when the lentils are ready, they should not \r\n'
      + 'be fully cooked. They should be only par-cooked and \r\n'
      + 'still have a bite to them as they need to finish \r\n'
      + 'cooking with the rice).\r\nNow, for the rice. \r\n'
      + 'Drain the rice from its soaking water. Combine the \r\n'
      + 'par-cooked lentils and the rice in the saucepan over \r\n'
      + 'medium-high heat with 1 tbsp cooking oil, salt, \r\n'
      + 'pepper, and coriander. Cook for 3 minutes, stirring \r\n'
      + 'regularly. Add warm water to cover the rice and \r\n'
      + 'lentil mixture by about 1 1/2 inches (you\u2019ll probably \r\n'
      + 'use about 3 cups of water here). Bring to a boil; \r\n'
      + 'the water should reduce a bit. Now cover and cook until \r\n'
      + 'all the liquid has been absorbed and both the rice and \r\n'
      + 'lentils are well cooked through (about 20 minutes).  \r\n'
      + 'Keep covered and undisturbed for 5 minutes or so.\r\n'
      + 'Now make the pasta. While the rice and lentils are \r\n'
      + 'cooking, make the pasta according to package instructions\r\n'
      + ' by adding the elbow pasta to boiling water with a \r\n'
      + 'dash of salt and a little oil. Cook until the pasta is \r\n'
      + 'al dente. Drain.\r\nCover the chickpeas and warm in \r\n'
      + 'the microwave briefly before serving.\r\n\r\n'
      + 'Make the crispy onion topping. \r\n\r\n'
      + 'Sprinkle the onion rings with salt, then toss them \r\n'
      + 'in the flour to coat. Shake off excess flour.\r\n'
      + 'In a large skillet, heat the cooking oil over \r\n'
      + 'medium-high heat, cook the onion rings, stirring often, \r\n'
      + 'until they turn a nice caramelized brown. \r\n'
      + 'Onions must be crispy, but not burned (15-20 minutes).',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/4er7mj1598733193.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=y0d2ZMZBW4Y',
      strIngredient1: 'Brown Lentils',
      strIngredient2: 'Rice',
      strIngredient3: 'Coriander',
      strIngredient4: 'Macaroni',
      strIngredient5: 'Chickpeas',
      strIngredient6: 'Onion',
      strIngredient7: 'Salt',
      strIngredient8: vegetableOil,
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 1/2 cups ',
      strMeasure2: '1 1/2 cups ',
      strMeasure3: '1/2 tsp',
      strMeasure4: '2 cups ',
      strMeasure5: 'Can',
      strMeasure6: '1 large',
      strMeasure7: 'Sprinking',
      strMeasure8: '1/2 cup ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.themediterraneandish.com/egyptian-koshari-recipe/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53013',
      strMeal: 'Big Mac',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'American',
      strInstructions: 'For the Big Mac sauce, \r\n'
      + 'combine all the ingredients in a bowl, \r\n'
      + 'season with salt and chill until ready to use.\r\n'
      + '2. To make the patties, season the mince \r\n'
      + 'with salt and pepper and form into 4 balls using\r\n'
      + ' about 1/3 cup mince each. Place each onto a square\r\n'
      + ' of baking paper and flatten to form into \r\n'
      + 'four x 15cm circles. Heat oil in a large \r\n'
      + 'frypan over high heat. In 2 batches, cook beef \r\n'
      + 'patties for 1-2 minutes each side until \r\n'
      + 'lightly charred and cooked through. Remove \r\n'
      + 'from heat and keep warm. Repeat with remaining two patties.\r\n'
      + '3. Carefully slice each burger bun into \r\n'
      + 'three acrossways, then lightly toast.\r\n'
      + '4. To assemble the burgers, spread a little \r\n'
      + 'Big Mac sauce over the bottom base. \r\n'
      + 'Top with some chopped onion, shredded lettuce, \r\n'
      + 'slice of cheese, beef patty and some \r\n'
      + 'pickle slices. Top with the middle bun layer, \r\n'
      + 'and spread with more Big Mac sauce, onion, \r\n'
      + 'lettuce, pickles, beef patty and then finish \r\n'
      + 'with more sauce. Top with burger lid to serve.\r\n'
      + '5. After waiting half an hour \r\n'
      + 'for your food to settle, go for a jog.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=C5J39YnnPsg',
      strIngredient1: mincedBeef,
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Sesame Seed Burger Buns',
      strIngredient4: 'Onion',
      strIngredient5: 'Iceberg Lettuce',
      strIngredient6: 'Cheese',
      strIngredient7: 'Dill Pickles',
      strIngredient8: 'Mayonnaise',
      strIngredient9: 'White Wine Vinegar',
      strIngredient10: 'Pepper',
      strIngredient11: 'Mustard',
      strIngredient12: 'Onion Salt',
      strIngredient13: 'Garlic Powder',
      strIngredient14: 'Paprika',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '400g',
      strMeasure2: '2 tbs',
      strMeasure3: '2',
      strMeasure4: 'Chopped',
      strMeasure5: '1/4 ',
      strMeasure6: '2 sliced',
      strMeasure7: '2 large',
      strMeasure8: '1 cup ',
      strMeasure9: '2 tsp',
      strMeasure10: 'Pinch',
      strMeasure11: '2 tsp',
      strMeasure12: '1 1/2 tsp ',
      strMeasure13: '1 1/2 tsp ',
      strMeasure14: '1/2 tsp',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53028',
      strMeal: 'Shawarma',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Egyptian',
      strInstructions: 'Combine the marinade ingredients\r\n'
      + ' in a large ziplock bag (or bowl).\r\n'
      + 'Add the chicken and use your hands to make \r\n'
      + 'sure each piece is coated. If using a \r\n'
      + 'ziplock bag, I find it convenient to close \r\n'
      + 'the bag then massage the bag to disperse the \r\n'
      + 'rub all over each chicken piece.\r\n'
      + 'Marinate overnight or up to 24 hours.\r\n'
      + 'Combine the Yoghurt Sauce ingredients \r\n'
      + 'in a bowl and mix. Cover and put in the \r\n'
      + 'fridge until required (it will last for 3 days in the fridge).\r\n'
      + 'Heat grill/BBQ (or large heavy based pan on stove) \r\n'
      + 'on medium high. You should not need to oil it because \r\n'
      + 'the marinade has oil in it and also thigh fillets \r\n'
      + 'have fat. But if you are worried then oil your hotplate/grill.\r\n'
      + ' (See notes for baking)\r\nPlace chicken on \r\n'
      + 'the grill and cook the first side for 4 to 5 \r\n'
      + 'minutes until nicely charred, then turn and cook\r\n'
      + ' the other side for 3 to 4 minutes (the 2nd side takes less time).\r\n'
      + 'Remove chicken from the grill and cover \r\n'
      + 'loosely with foil. Set aside to rest for 5 minutes.\r\n'
      + 'TO SERVE\r\nSlice chicken and pile onto platter \r\n'
      + 'alongside flatbreads, Salad and the Yoghurt Sauce.\r\n'
      + 'To make a wrap, get a piece of flatbread and\r\n'
      + ' smear with Yoghurt Sauce. Top with a bit of \r\n'
      + 'lettuce and tomato and Chicken Shawarma. Roll up and enjoy!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=3lxUIeKDgic',
      strIngredient1: 'Chicken Thighs',
      strIngredient2: 'Coriander',
      strIngredient3: 'Cumin',
      strIngredient4: 'Cardamom',
      strIngredient5: 'Cayenne Pepper',
      strIngredient6: 'Paprika',
      strIngredient7: lemonJuice,
      strIngredient8: 'Olive Oil',
      strIngredient9: 'Greek Yogurt',
      strIngredient10: garlicClove,
      strIngredient11: 'Cumin',
      strIngredient12: lemonJuice,
      strIngredient13: 'Lettuce',
      strIngredient14: 'Tomato',
      strIngredient15: 'Pita Bread',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 kg',
      strMeasure2: '1 tbs',
      strMeasure3: '1 tbs',
      strMeasure4: '1 tbs',
      strMeasure5: '1 tsp ',
      strMeasure6: '2 tsp',
      strMeasure7: '2 tbs',
      strMeasure8: '3 tbs',
      strMeasure9: '1 cup ',
      strMeasure10: '1',
      strMeasure11: '1 tsp ',
      strMeasure12: 'Splash',
      strMeasure13: 'Sliced',
      strMeasure14: 'Sliced',
      strMeasure15: '6',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.recipetineats.com/chicken-sharwama-middle-eastern/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    }],
};

export const mockDrinksData = {
  drinks: [
    {
      idDrink: '15997',
      strDrink: 'GG',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Optional alcohol',
      strGlass: 'Collins Glass',
      strInstructions: 'Pour the Galliano liqueur over ice. \r\n'
      + 'Fill the remainder of the glass with ginger ale and \r\n'
      + 'thats all there is to it. You now have a your very own GG.',
      strInstructionsES: null,
      strInstructionsDE: 'Den Galliano-Lik\u00F6r \u00FCber Eis \r\n'
      + 'gie\u00DFen. F\u00FCllen Sie den Rest des Glases mit \r\n'
      + 'Ginger Ale und das ist alles, was dazu geh\u00F6rt. \r\n'
      + 'Du hast jetzt ein eigenes GG.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare il liquore Galliano su ghiaccio.\r\n'
      + 'Riempi il resto del bicchiere con ginger ale e questo \u00E8 tutto.\r\n'
      + 'Ora hai il tuo GG personale.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
      strIngredient1: 'Galliano',
      strIngredient2: 'Ginger ale',
      strIngredient3: 'Ice',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 1/2 shots ',
      strMeasure2: null,
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-18 22:06:00',
    },
    {
      idDrink: '17222',
      strDrink: 'A1',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: cocktailGlass,
      strInstructions: 'Pour all ingredients \r\n'
      + 'into a cocktail shaker, mix and\r\n'
      + ' serve over ice into a chilled glass.',
      strInstructionsES: 'Vierta todos los \r\n'
      + 'ingredientes en una coctelera, \r\n'
      + 'mezcle y sirva con hielo en un vaso fr\u00EDo.',
      strInstructionsDE: 'Alle Zutaten in \r\n'
      + 'einen Cocktailshaker geben, mischen und\r\n'
      + ' \u00FCber Eis in ein gek\u00FChltes Glas servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare tutti gli \r\n'
      + 'ingredienti in uno shaker, mescolare \r\n'
      + 'e servire con ghiaccio in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
      strIngredient1: 'Gin',
      strIngredient2: grandMarnier,
      strIngredient3: lemonJuice,
      strIngredient4: 'Grenadine',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 3/4 shot ',
      strMeasure2: '1 Shot ',
      strMeasure3: '1/4 Shot',
      strMeasure4: '1/8 Shot',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 21:42:09',
    },
    {
      idDrink: '17225',
      strDrink: 'Ace',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake all the ingredients\r\n'
      + ' in a cocktail shaker and ice then strain\r\n'
      + ' in a cold glass.',
      strInstructionsES: 'Agite todos los ingredientes\r\n'
      + ' en una coctelera con hielo y entonces \r\n'
      + 'cu\u00E9lelos sobre un vaso enfriado.',
      strInstructionsDE: 'Alle Zutaten in einem \r\n'
      + 'Cocktailshaker mit Eis sch\u00FCtteln \r\n'
      + 'und dann in einem kalten Glas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli \r\n'
      + 'ingredienti in uno shaker e ghiaccio,\r\n'
      + ' quindi filtrare in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grenadine',
      strIngredient3: 'Heavy cream',
      strIngredient4: 'Milk',
      strIngredient5: 'Egg White',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 shots ',
      strMeasure2: '1/2 shot ',
      strMeasure3: '1/2 shot ',
      strMeasure4: '1/2 shot',
      strMeasure5: '1/2 Fresh',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 22:05:06',
    },
    {
      idDrink: '14229',
      strDrink: '747',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'pour kaluha, then \r\n'
      + 'Baileys, then Frangelico not \r\n'
      + 'chilled and not layered -- SERVE!!!',
      strInstructionsES: null,
      strInstructionsDE: 'Gie\u00DFen Sie kaluha,\r\n'
      + ' dann Baileys, dann Frangelico \r\n'
      + 'nicht gek\u00FChlt und nicht geschichtet\r\n'
      + ' -- SERVE!!!!!!!!',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa Kahlua, Baileys\r\n'
      + ' e poi Frangelico.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg',
      strIngredient1: 'Kahlua',
      strIngredient2: baileysIrishCream,
      strIngredient3: 'Frangelico',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 part ',
      strMeasure2: '1/3 part ',
      strMeasure3: '1/3 part ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:28:26',
    },
    {
      idDrink: '17203',
      strDrink: 'Kir',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Wine Glass',
      strInstructions: 'Add the cr\u00E8me \r\n'
      + 'de cassis to the bottom of the \r\n'
      + 'glass, then top up with wine.',
      strInstructionsES: null,
      strInstructionsDE: 'Gib die Creme de \r\n'
      + 'Cassis auf den Boden des Glases\r\n'
      + ' und f\u00FCge dann Wein hinzu.',
      strInstructionsFR: null,
      strInstructionsIT: 'Aggiungere la \r\n'
      + 'cr\u00E8me de cassis sul fondo \r\n'
      + 'del bicchiere, quindi rabboccare con il vino.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg',
      strIngredient1: 'Creme de Cassis',
      strIngredient2: 'Champagne',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 part ',
      strMeasure2: '5 parts ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 17:38:14',
    },
    {
      idDrink: '13501',
      strDrink: 'ABC',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'Layered in a shot glass.',
      strInstructionsES: 'Coloque todos los ingredientes en un vaso de chupito.',
      strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
      strInstructionsFR: null,
      strInstructionsIT:
      'Versa in ordine di lettera i vari ingredienti.'
      + "1/3 del bicchiere va riempito con l'Amaretto, "
      + '1/3 di Baileys e il restante di Cognac.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
      strIngredient1: 'Amaretto',
      strIngredient2: baileysIrishCream,
      strIngredient3: 'Cognac',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 ',
      strMeasure2: '1/3 ',
      strMeasure3: '1/3 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:32:08',
    },
    {
      idDrink: '15288',
      strDrink: '252',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'Add both ingredients to shot glass, shoot, and get drunk quick',
      strInstructionsES: null,
      strInstructionsDE: 'Beide Zutaten in ein Schnapsglas geben.',
      strInstructionsFR: null,
      strInstructionsIT: 'Aggiungi entrambi \r\n'
      + 'gli ingredienti al bicchierino, \r\n'
      + 'bevi e ubriacati velocemente',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg',
      strIngredient1: '151 proof rum',
      strIngredient2: 'Wild Turkey',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/2 shot Bacardi ',
      strMeasure2: '1/2 shot ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-18 22:32:42',
    },
    {
      idDrink: '13938',
      strDrink: 'AT&T',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball Glass',
      strInstructions: 'Pour Vodka and Gin over ice, add Tonic and Stir',
      strInstructionsES: 'Vierta el vodka y la \r\n'
      + 'ginebra sobre el hielo, agregue \r\n'
      + 'la t\u00F3nica y revuelva.',
      strInstructionsDE: 'Wodka und Gin \u00FCber \r\n'
      + 'das Eis gie\u00DFen, Tonic \r\n'
      + 'hinzuf\u00FCgen und umr\u00FChren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare la vodka e il gin sul ghiaccio,'
      + "aggiungere l'acqua tonica e mescolare",
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg',
      strIngredient1: 'Absolut Vodka',
      strIngredient2: 'Gin',
      strIngredient3: 'Tonic water',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '4 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-04-24 22:00:19',
    },
    {
      idDrink: '17141',
      strDrink: 'Smut',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Punch / Party Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Beer mug',
      strInstructions: 'Throw it all together and serve real cold.',
      strInstructionsES: null,
      strInstructionsDE: 'Sch\u00FCtte alles zusammen und serviere es kalt.',
      strInstructionsFR: null,
      strInstructionsIT: 'Metti tutto insieme e servi freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      strIngredient1: 'Red wine',
      strIngredient2: 'Peach schnapps',
      strIngredient3: 'Pepsi Cola',
      strIngredient4: 'Orange juice',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 part ',
      strMeasure2: '1 shot ',
      strMeasure3: '1/3 part ',
      strMeasure4: '1/3 part ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 16:23:32',
    },
    {
      idDrink: '13332',
      strDrink: 'B-53',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Collins Glass',
      strInstructions: 'Layer the Kahlua, \r\n'
      + 'Sambucca and Grand Marnier into \r\n'
      + 'a shot glas in that order. Better than B-52',
      strInstructionsES: null,
      strInstructionsDE: 'Schichte die Kahlua,\r\n'
      + ' Sambucca und Grand Marnier in dieser\r\n'
      + ' Reihenfolge in ein Schnapsglas ein. Besser als B-52',
      strInstructionsFR: null,
      strInstructionsIT:
      "Metti Kahlua, Sambuca e Grand Marnier in un bicchierino in quest'ordine. ",
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg',
      strIngredient1: 'Kahlua',
      strIngredient2: 'Sambuca',
      strIngredient3: grandMarnier,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 shot ',
      strMeasure2: '1/3 shot ',
      strMeasure3: '1/3 shot ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-04-28 18:53:43',
    },
    {
      idDrink: '17837',
      strDrink: 'Adam',
      strDrinkAlternate: null,
      strTags: 'Alcoholic,Holiday',
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: cocktailGlass,
      strInstructions: 'In a shaker half-filled \r\n'
      + 'with ice cubes, combine all of the \r\n'
      + 'ingredients. Shake well. Strain into a cocktail glass.',
      strInstructionsES: 'Mezclar todos los \r\n'
      + 'ingredientes en una coctelera con \r\n'
      + 'cubitos de hielo hasta la mitad. \r\n'
      + 'Agitar bien. Colar el contenido \r\n'
      + 'en un vaso de c\u00F3ctel.',
      strInstructionsDE: 'In einem Shaker, der\r\n'
      + ' halb mit Eisw\u00FCrfeln gef\u00FCllt\r\n'
      + ' ist, alle Zutaten vermengen. Gut \r\n'
      + 'sch\u00FCtteln. In ein Cocktailglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito\r\n'
      + ' a met\u00E0 con cubetti di ghiaccio,\r\n'
      + ' unire tutti gli ingredienti.Agitare\r\n'
      + ' bene.Filtrare in un bicchiere da cocktail.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
      strIngredient1: 'Dark rum',
      strIngredient2: lemonJuice,
      strIngredient3: 'Grenadine',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 tsp ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-09-02 11:29:29',
    },
    {
      idDrink: '14610',
      strDrink: 'ACID',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'Poor in the 151 first \r\n'
      + 'followed by the 101 served with a \r\n'
      + 'Coke or Dr Pepper chaser.',
      strInstructionsES: 'Vierta primero el Bacardi\r\n'
      + ' 151, seguido del Wild Turkey 101 y sirva\r\n'
      + ' con Coca-Cola o Dr Pepper.',
      strInstructionsDE: 'Gering den 151 gefolgt\r\n'
      + ' von der 101, die mit einer Cola oder\r\n'
      + ' Dr. Pepper Chaser serviert wird.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa prima il Bacardi\r\n'
      + ' 151 seguito dal 101, servito con una Coca-Cola.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
      strIngredient1: '151 proof rum',
      strIngredient2: 'Wild Turkey',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz Bacardi ',
      strMeasure2: '1 oz ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-11-15 11:28:37',
    },
    {
      idDrink: '16262',
      strDrink: 'H.D.',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Coffee / Tea',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Beer mug',
      strInstructions: 'Mix the whisky and Baileys Cream in a\r\n'
      + ' beer-glass (at least 50 cl). Fill the rest of the glass with coffee.',
      strInstructionsES: null,
      strInstructionsDE: 'Den Whisky und die Baileys Cream in \r\n'
      + 'einem Bierglas (mind. 50 cl) mischen. F\u00FCllen Sie\r\n'
      + ' den Rest des Glases mit Kaffee.',
      strInstructionsFR: null,
      strInstructionsIT: 'Mescolare il whisky e la crema \r\n'
      + 'di Baileys in un bicchiere da birra (almeno 50 cl).\r\n'
      + 'Riempi il resto del bicchiere di caff\u00E8.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/upusyu1472667977.jpg',
      strIngredient1: 'Whisky',
      strIngredient2: baileysIrishCream,
      strIngredient3: 'Coffee',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '4 cl ',
      strMeasure2: '8 cl ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:26:18',
    },
    {
      idDrink: '15853',
      strDrink: 'B-52',
      strDrinkAlternate: null,
      strTags: 'IBA,NewEra',
      strVideo: null,
      strCategory: 'Shot',
      strIBA: 'New Era Drinks',
      strAlcoholic: 'Alcoholic',
      strGlass: shotGlass,
      strInstructions: 'Layer ingredients into a shot glass. Serve with a stirrer.',
      strInstructionsES: null,
      strInstructionsDE: 'Zutaten in ein Schnapsglas schichten. \r\n'
      + 'Mit einem R\u00FChrstab servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Metti gli ingredienti in un bicchiere da shot a strati.\r\n'
      + 'Servire con una paletta.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg',
      strIngredient1: baileysIrishCream,
      strIngredient2: grandMarnier,
      strIngredient3: 'Kahlua',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 ',
      strMeasure2: '1/3 ',
      strMeasure3: '1/4 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 18:07:51',
    },
    {
      idDrink: '17208',
      strDrink: 'Rose',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: 'Contemporary Classics',
      strAlcoholic: 'Alcoholic',
      strGlass: cocktailGlass,
      strInstructions: 'Shake together in a cocktail \r\n'
      + 'shaker, then strain into chilled glass. Garnish and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'In einem Cocktailshaker vermengen und\r\n'
      + ' dann in ein gek\u00FChltes Glas abseihen. Garnieren und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare insieme in uno shaker,\r\n'
      + ' quindi filtrare in un bicchiere freddo.\r\nGuarnire e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/8kxbvq1504371462.jpg',
      strIngredient1: 'Dry Vermouth',
      strIngredient2: 'Gin',
      strIngredient3: 'Apricot brandy',
      strIngredient4: lemonJuice,
      strIngredient5: 'Grenadine',
      strIngredient6: 'Powdered sugar',
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1/2 oz ',
      strMeasure4: '1/2 tsp ',
      strMeasure5: '1 tsp ',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 17:57:42',
    }],
};
